name: Build Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Documentation
        run: |
          sphinx-build -b html docs/ docs/_build/html/

      - name: Ensure Static Files Are Present
        run: |
          ls -p docs/_build/html/

      - name: Disable Jekyll Processing
        run: touch docs/_build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to the root of gh-pages
          folder: docs/_build/html  # Ensure this points to the html folder
          token: ${{ secrets.GH_PAT }}
          clean: true  # Deletes old files before deployment